#
# Definition of all trackable objects
# Identifier corresponds to Streaming ID set in Motive
#
mocap_node:
  ros__parameters:
    rigid_bodies:
      '1':
        pose2d: optitrack/drone/pose_raw
    free_markers: true # set to true to publish marker positions for markers not in rigid bodies
    optitrack_config:
      # should match the Multicast Interface in Motive streaming panel
      multicast_address: 239.255.42.99
      command_port: 1510
      data_port: 1511
      enable_optitrack: true
