h1/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 1.0
    maxiter: 20
    nx: 6
    nu: 3
    nxd: 12
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 144 #N=7
    # idx_u1: 147 #N=7
    # idx_u0: 198
    # idx_u1: 201
    idx_u0: 378
    idx_u1: 381
    # idx_x0: 48 #N=7
    # idx_x0: 66
    idx_x0: 126
    Nagents: 4
    my_id: 1
    folder_name_sprob: "sProb_chain_QP_N20_acc_050_damped"
/**:
#control_lqr:
  ros__parameters:
    period: 0.01

    weight_x: 14.0
    weight_y: 14.0
    weight_v_x: 0.01
    weight_v_y: 0.01
    weight_yaw: 10.0
    weight_w_z: 0.01

    weight_a_x: 10.0
    weight_a_y: 10.0
    weight_w_dot_z: 10.0