h0/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 1.0
    maxiter: 20
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 96 #N=7
    # idx_u1: 99 #N=7
    # idx_u0: 132
    # idx_u1: 135
    idx_u0: 252
    idx_u1: 255
    idx_x0: 0
    Nagents: 4
    my_id: 0
    folder_name_sprob: "sProb_chain_QP_N20_acc_050_damped"
    file_name_xd_trajectory: ""
    file_name_ud_trajectory: ""
