h3/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 2.0
    maxiter: 20
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 6
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 96
    # idx_u1: 99
    # idx_u0: 132
    # idx_u1: 135
    idx_u0: 252
    idx_u1: 255
    # idx_x0: 48 #N=7
    # idx_x0: 66
    idx_x0: 126
    Nagents: 4
    Nobs: 0
    my_id: 3
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "sProb_chain_QP_N20_4"