h1/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    control_period: 0.01
    rho: 2.0
    maxiter: 20
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 144 #N=7
    # idx_u1: 147 #N=7
    # idx_u0: 198
    # idx_u1: 201
    idx_u0: 378
    idx_u1: 381
    # idx_x0: 48 #N=7
    # idx_x0: 66
    idx_x0: 126
    Nagents: 4
    Nobs: 0
    my_id: 1
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "QP_N20"