h2/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 2.0
    maxiter: 20
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 144 #N=7
    # idx_u1: 147 #N=7
    # idx_u0: 198
    # idx_u1: 201
    idx_u0: 378
    idx_u1: 381
    # idx_x0: 48 #N=7
    # idx_x0: 66
    idx_x0: 126
    Nagents: 4
    my_id: 2
    folder_name_sprob: "sProb_chain_QP_N20_acc_050_damped"