h0/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 5.0
    maxiter: 1
    max_inner_iter: 30
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 252
    idx_u1: 255
    idx_x0: 0
    Nagents: 4
    my_id: 0
    folder_name_sprob: "sProb_chain_QCQP_N20"
    file_name_xd_trajectory: ""
    file_name_ud_trajectory: ""
