h0/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 5.0
    maxiter: 10
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 252
    idx_u1: 255
    idx_x0: 0
    Nagents: 4
    Nobs: 1
    my_id: 0
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "QCQP_obs_N20"
