h1/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 5.0
    maxiter: 30
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 378
    idx_u1: 381
    idx_x0: 126
    Nagents: 4
    my_id: 1
    folder_name_sprob: "sProb_chain_QCQP_N20"
