h3/dmpc:
  ros__parameters:
    dmpc_period: 0.150
    control_period: 0.0
    rho: 4.0
    maxiter: 6
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 6
    nud: 0
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 96
    idx_u1: 99
    idx_x0: 48
    Nagents: 4
    Nobs: 1
    my_id: 3
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "QCQP_N7_obs"