navigation:
  ros__parameters:
    period: 0.005

    state_cov_x: 2.2603e-06
    state_cov_y: 2.2603e-06
    state_cov_yaw: 6.7379e-03
    state_cov_x_dot: 1.3265e-04
    state_cov_y_dot: 1.3265e-04
    state_cov_yaw_dot: 1.4564e-04
    state_cov_x_dot_dot: 1.3665e+03
    state_cov_y_dot_dot: 1.3665e+03
    state_cov_yaw_dot_dot: 4.3901e+03

    control_cov_a_x: 1e3
    control_cov_a_y: 1e3
    control_cov_w_dot_z: 1e3

    sensor_acc_cov_x: 1e6
    sensor_acc_cov_y: 1e6
    sensor_gyro_cov_z: 1e6

    sensor_mouse_cov_x: 1e6
    sensor_mouse_cov_y: 1e6

    sensor_pose_cov_x: 2.2603e-06
    sensor_pose_cov_y: 2.2603e-06
    sensor_pose_cov_yaw: 2.2603e-06
