time_step: 0.5 

names: [o4]
ids: [4]

trajectory:
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: -0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: 0.0
        yaw: 0.0

  - step:
      - id: 4
        x: -0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: 0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: -0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: 0.0
        yaw: 0.0

  - step:
      - id: 4
        x: -0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: 0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: -0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: 0.0
        yaw: 0.0

  - step:
      - id: 4
        x: -0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: 0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: -0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: 0.0
        yaw: 0.0

  - step:
      - id: 4
        x: -0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: 0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: -0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: 0.0
        yaw: 0.0

  - step:
      - id: 4
        x: -0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: -0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: -0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.1
        yaw: 0.0
  
  - step:
      - id: 4
        x: 0.03827
        y: 0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: 0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: 0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: 0.09239
        y: -0.03827
        yaw: 0.0
  - step:
      - id: 4
        x: 0.07071
        y: -0.07071
        yaw: 0.0
  - step:
      - id: 4
        x: 0.03827
        y: -0.09239
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.1
        yaw: 0.0

  

  