time_step: 0.500000

names: [o4]
ids: [4]

trajectory:
  - step:
      - id: 4
        x: 0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.000000
        y: -0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.300000
        y: -0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.000000
        y: 0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.300000
        y: 0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.000000
        y: -0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.300000
        y: -0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.000000
        y: 0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.300000
        y: 0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.000000
        y: -0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.300000
        y: -0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.000000
        y: 0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.300000
        y: 0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.000000
        y: -0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.300000
        y: -0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.000000
        y: 0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.300000
        y: 0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.000000
        y: -0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: -0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: -0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: -0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.300000
        y: -0.000000
        yaw: 0.0
  - step:
      - id: 4
        x: -0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: -0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: -0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: -0.000000
        y: 0.300000
        yaw: 0.0
  - step:
      - id: 4
        x: 0.114805
        y: 0.277164
        yaw: 0.0
  - step:
      - id: 4
        x: 0.212132
        y: 0.212132
        yaw: 0.0
  - step:
      - id: 4
        x: 0.277164
        y: 0.114805
        yaw: 0.0
  - step:
      - id: 4
        x: 0.300000
        y: 0.000000
        yaw: 0.0
