time_step: 1

names: [o4]
ids: [4]

trajectory:
  - step:
      - id: 4
        x: 0.7
        y: 0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.4
        y: 0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.3
        y: 0.3
        yaw: 0.0
  - step:
      - id: 4
        x: 0.2
        y: 0.2
        yaw: 0.0
  - step:
      - id: 4
        x: 0.1
        y: 0.1
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: 0.0
        yaw: 0.0
  - step:
      - id: 4
        x: -0.1
        y: -0.1
        yaw: 0.0
  - step:
      - id: 4
        x: -0.2
        y: -0.2
        yaw: 0.0
  - step:
      - id: 4
        x: -0.3
        y: -0.3
        yaw: 0.0
  - step:
      - id: 4
        x: -0.4
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: -0.6
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: -0.3
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.0
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.3
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.6
        y: -0.4
        yaw: 0.0
  - step:
      - id: 4
        x: 0.9
        y: -0.4
        yaw: 0.0
  

  