time_step: 10 

names: [o3]
ids: [3]

trajectory:
  - step:
      - id: 3
        x: 0.9
        y: 0.3
        yaw: 0.0
  - step:
      - id: 3
        x: 0.2
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.8
        y: 0.0
        yaw: 0.0
  

  