time_step: 10 

names: [o3]
ids: [3]

trajectory:
  - step:
      - id: 3
        x: 0.9
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.85
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.8
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.75
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.7
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.65
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.6
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.55
        y: 0.0
        yaw: 0.0
  - step:
      - id: 3
        x: 0.5
        y: 0.0
        yaw: 0.0
  

  