h0/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 0.1
    maxiter: 30
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 132
    nud: 60
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 252
    idx_u1: 255
    idx_x0: 0
    Nagents: 4
    Nobs: 0
    my_id: 0
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "sProb_chain_QCQP_N20_050_traj"
