h2/dmpc:
  ros__parameters:
    dmpc_period: 0.050
    rho: 0.1
    maxiter: 30
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 60
    N: 20
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 378
    idx_u1: 381
    idx_x0: 126
    Nagents: 4
    my_id: 2
    folder_name_sprob: "sProb_chain_QP_N20_050_traj"