h0/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 0.1
    maxiter: 30
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 72
    nud: 30
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 132
    idx_u1: 135
    idx_x0: 0
    Nagents: 4
    my_id: 0
    folder_name_sprob: "sProb_chain_QCQP_N10_100_traj"
