h2/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 0.1
    maxiter: 30
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 30
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 198
    idx_u1: 201
    idx_x0: 66
    Nagents: 4
    Nobs: 0
    my_id: 2
    folder_name_sprob: "sProb_chain_QCQP_N10_100_traj"
