h2/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 2.0
    maxiter: 6
    max_outer_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 198
    idx_u1: 201
    idx_x0: 66
    Nagents: 4
    Nobs: 0
    my_id: 2
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "sProb_chain_QP_N10_4"