h1/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 5.0
    maxiter: 5
    max_inner_iter: 1
    nx: 6
    nu: 3
    nxd: 12
    nud: 0
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 198
    idx_u1: 201
    idx_x0: 66
    Nagents: 4
    my_id: 1
    folder_name_sprob: "sProb_chain_QP_N10_acc_100_damped"
    file_name_xd_trajectory: ""
    file_name_ud_trajectory: ""