# holohover_utils/config/common/control_mpc_play_config.yaml

h0:
  mpc: 
    ros__parameters:
      period: 0.06
      solver: ipopt
      weight_motor: 50.0
      weight_momentum: 1800.0
      weight_distance: 100.0
      weight_comehome: 5000.0
      scale_distance: 0.2
      scale_momentum: 0.02
      weight_yaw: 1.0
      weight_w_z: 1.0

      control_limit : 0.35

      # Not used
      weight_x : 0.0 
      weight_y: 10.0 # sharpness for switching mode
      weight_v_x : 0.0
      weight_v_y : 0.0
     
      home_x: 0.9
      home_y: 0.0
      goal_x: -1.0
      goal_y: 0.0

h1:
  mpc:
    ros__parameters:
      period: 0.06
      solver: ipopt
      weight_motor: 50.0
      weight_momentum: 1500.0
      weight_distance: 100.0
      weight_comehome: 5000.0
      scale_distance: 0.2
      scale_momentum: 0.05
      weight_yaw: 1.0
      weight_w_z: 1.0

      control_limit : 0.35

      # Not used
      weight_x : 0.0 
      weight_y: 10.0 # sharpness
      weight_v_x : 0.0
      weight_v_y : 0.0
      
      home_x: -0.9
      home_y: 0.0
      goal_x: 1.0
      goal_y: 0.0