# holohover_utils/config/common/control_mpc_play_config.yaml
h0:
  mpc: 
    ros__parameters:
      period: 0.04
      solver: ipopts
      weight_motor: 1.0
      weight_momentum: 10.0
      weight_distance: 10.0
      weight_comehome: 100.0
      scale_distance: 0.5 # minimum 0.5
      scale_momentum: 0.3
      weight_yaw: 10.0
      weight_w_z: 1.0

      control_limit : 1.0

      controller_delay : 0.04

      # Not used
      weight_x : 20.0 # strike mode
      weight_y: 0.0 
      weight_v_x : 0.7
      weight_v_y : 0.6
     
      home_x: 0.9
      home_y: 0.0
      goal_x: -1.0
      goal_y: 0.0

h1:
  mpc:
    ros__parameters:
      period: 0.04
      solver: ipopt
      weight_motor: 0.01
      weight_momentum: 200.0
      weight_distance: 10.0
      weight_comehome: 500.0
      scale_distance: 0.5
      scale_momentum: 0.3
      weight_yaw: 20.0
      weight_w_z: 1.0

      control_limit : 1.0

      controller_delay : 0.04

      # Not used
      weight_x : 0.0 # sharpness
      weight_y: 0.0 
      weight_v_x : 0.7
      weight_v_y : 0.6
      
      home_x: -0.9
      home_y: 0.0
      goal_x: 1.0
      goal_y: 0.0