control_dmpc3:
  ros__parameters:
    period: 40.0
    rho: 1.0
    maxiter: 10
    nx: 6
    nu: 3
    nxd: 6
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 96
    idx_u1: 99
    Nagents: 4
    my_id: 3
    folder_name_sprob: "/home/mgoestom@ie3.e-technik.tu-dortmund.de/holohover_ws/src/holohover/holohover_gnc/ocp_specs/sProb_chain_QP_N7_acc"
