holohover_dmpc_trigger:
  ros__parameters:
    period: 0.100
    rho: 1.0
    maxiter: 50
    nx: 6
    nu: 3
    nxd: 12
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 96
    idx_u1: 99
    idx_x0: 0
    Nagents: 4
    my_id: 0
    folder_name_sprob: "../../holohover_gnc/ocp_specs/sProb_chain_QP_N7_acc"