time_step: 10 

names: [h0, h1, h2]
ids: [0, 1, 2]
neighbors: 
  - 0: [1]
  - 1: [2]
  - 2: []

trajectory:
  - step:
      - id: 0
        x: -0.9
        y: 0.3
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: -0.3
        y: 0.0
        yaw: 0.0
# Continue adding trajectory data for each timestep as needed
