time_step: 0.5 

names: [h0, h1, h2, h3]
ids: [0, 1, 2, 3]
neighbors: 
  - 0: [1]
  - 1: [2]
  - 2: [3]
  - 3: [] 

trajectory:
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  - step:
      - id: 0
        x: -0.6
        y: -0.15
        yaw: 0.0
      - id: 1
        x: -0.3
        y: 0.0
        yaw: 0.0
      - id: 2
        x: 0.0
        y: 0.3
        yaw: 0.0
      - id: 3
        x: 0.3
        y: 0.0
        yaw: 0.0
  