h1/dmpc:
  ros__parameters:
    period: 40.0
    rho: 1.0
    maxiter: 10
    nx: 6
    nu: 3
    nxd: 12
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 144
    idx_u1: 147
    idx_x0: 48
    Nagents: 4
    my_id: 1
    folder_name_sprob: "../../holohover_dmpc/ocp_specs/sProb_chain_QP_N7_acc"