h2/dmpc:
  ros__parameters:
    period: 0.100
    rho: 1.0
    maxiter: 5
    nx: 6
    nu: 3
    nxd: 12
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 144
    idx_u1: 147
    idx_x0: 48
    Nagents: 4
    my_id: 2
    folder_name_sprob: "sProb_chain_QP_N7_acc"