h3/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 4.0
    maxiter: 20
    nx: 6
    nu: 3
    nxd: 6
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    # idx_u0: 96
    # idx_u1: 99
    idx_u0: 132
    idx_u1: 135
    # idx_x0: 48 #N=7
    idx_x0: 66
    Nagents: 4
    my_id: 3
    folder_name_sprob: "sProb_chain_QP_N10_acc"
/**:
#control_lqr:
  ros__parameters:
    period: 0.01

    weight_x: 14.0
    weight_y: 14.0
    weight_v_x: 0.01
    weight_v_y: 0.01
    weight_yaw: 10.0
    weight_w_z: 0.01

    weight_a_x: 10.0
    weight_a_y: 10.0
    weight_w_dot_z: 10.0
