h2/dmpc:
  ros__parameters:
    dmpc_period: 0.100
    rho: 5.0
    maxiter: 10
    nx: 6
    nu: 3
    nxd: 12
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 144
    idx_u1: 147
    idx_x0: 48
    Nagents: 4
    my_id: 2
    folder_name_sprob: "sProb_chain_QP_N7_acc"
/**:
#control_lqr:
  ros__parameters:
    period: 0.01

    weight_x: 14.0
    weight_y: 14.0
    weight_v_x: 0.1
    weight_v_y: 0.1
    weight_yaw: 10.0
    weight_w_z: 0.1

    weight_a_x: 1.0
    weight_a_y: 1.0
    weight_w_dot_z: 1.0