holohover_dmpc_trigger:
  ros__parameters:
    dmpc_period: 0.050
    rho: 5.0
    maxiter: 3
    max_inner_iter: 5
    nx: 6
    nu: 3
    nxd: 12
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    idx_u0: 96
    idx_u1: 99
    idx_x0: 0
    Nagents: 4
    my_id: 0
    folder_name_sprob: "sProb_chain_QP_N7_acc"