/**:
  ros__parameters:
    dmpc_period: 0.150
    control_period: 0.01
    rho: 0.1
    maxiter: 6
    max_outer_iter: 1
    polish: false
    nx: 6
    nu: 3

    nxd: [54, 12, 12,  6]
    nud: [21, 21, 21, 21]
    
    N: 7
    idx_eqx0: 0
    idx_equ0: 6
    
    idx_u0: [96, 144, 144, 96]
    idx_u1: [99, 147, 147, 99]
    idx_x0: [ 0,  48,  48, 48] 
    
    Nagents: 4
    Nobs: 1
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "QCQP_N7_traj_obs"
