/**:
  ros__parameters:
    dmpc_period: 0.100
    control_period: 0.01
    rho: 4.0
    maxiter: 6
    max_outer_iter: 1
    polish: false
    nx: 6
    nu: 3

    nxd: [12, 12, 12, 6]
    nud: [0, 0, 0, 0]
    
    N: 10
    idx_eqx0: 0
    idx_equ0: 6
    
    idx_u0: [132, 198, 198, 132]
    idx_u1: [135, 201, 201, 135]
    idx_x0: [  0,  66,  66,  66]
    
    Nagents: 4
    Nobs: 0
    max_wait_time: 0.025
    max_wait_fraction: 0.75
    folder_name_sprob: "QCQP_N10_2"
